import test from 'node:test'
import assert from 'node:assert/strict'

import {
  buildQuestionExportRows,
  evaluateAnswer,
  filterQuestionExportRows,
  formatExportContent,
  normalizeQuestionBank,
} from './exerciseCore.js'

test('normalizes imported question-bank objects', () => {
  const questions = normalizeQuestionBank({
    body: [
      {
        questions: ['下列属于正反馈的是'],
        type: ['多选题'],
        type_code: '2',
        options: ['排尿', '血压稳定', '分娩', '凝血'],
        answers: ['ACD'],
        answers_matching_index: [0, 2, 3],
      },
    ],
  })

  assert.equal(questions.length, 1)
  assert.equal(questions[0].type, 'multiple')
  assert.deepEqual(questions[0].answerIndexes, [0, 2, 3])
})

test('removes accidental spaces between Chinese characters only', () => {
  const [question] = normalizeQuestionBank({
    body: [
      {
        questions: ['关 于 生 理 学 这 门 学 科'],
        type_code: '1',
        options: ['维生素 B12', '细 胞 膜', 'A 选项'],
        answers: ['A'],
      },
    ],
  })

  assert.equal(question.title, '关于生理学这门学科')
  assert.equal(question.options[0], '维生素 B12')
  assert.equal(question.options[1], '细胞膜')
  assert.equal(question.options[2], 'A 选项')
})

test('accepts JSON generated by tools/json-export-tool', () => {
  const questions = normalizeQuestionBank({
    head: {
      filename: '工具生成题库',
      course: '测试课程',
    },
    body: [
      {
        questions: ['关于细胞膜的描述，正确的是'],
        type: ['单选题'],
        type_code: '1',
        options: ['由脂质双层构成', '不含蛋白质', '不能进行物质交换'],
        answers: ['A'],
        answers_matching_index: [0],
        analysis: ['细胞膜以脂质双层为基本骨架。'],
      },
      {
        questions: ['钠钾泵属于主动转运'],
        type: ['判断题'],
        type_code: '3',
        options: ['错误', '正确'],
        answers: ['正确'],
        answers_matching_index: [1],
      },
    ],
  }, 'tool-output')

  assert.equal(questions.length, 2)
  assert.equal(questions[0].type, 'single')
  assert.deepEqual(questions[0].answerIndexes, [0])
  assert.equal(questions[1].type, 'judge')
  assert.equal(evaluateAnswer(questions[1], 1).correct, true)
})

test('checks single and multiple selections', () => {
  const [question] = normalizeQuestionBank({
    body: [
      {
        questions: ['正确答案是 B'],
        type_code: '1',
        options: ['A 项', 'B 项'],
        answers: ['B'],
      },
    ],
  })

  assert.equal(evaluateAnswer(question, 1).correct, true)
  assert.equal(evaluateAnswer(question, 0).correct, false)
})

test('checks fill blanks by separated parts with loose text normalization', () => {
  const [question] = normalizeQuestionBank({
    body: [
      {
        questions: ['Fill blanks'],
        type_code: '4',
        answers: ['Alpha；Ｂ-12|gamma, delta'],
      },
    ],
  })

  assert.equal(evaluateAnswer(question, 'alpha;b12|GAMMA delta').correct, true)
  assert.equal(evaluateAnswer(question, 'alpha;gamma delta|b12').correct, false)
  assert.equal(evaluateAnswer(question, 'alpha b12 gamma delta').correct, false)
  assert.equal(evaluateAnswer(question, 'alpha;b12|GAMMA delta').expectedText, question.answerText)
})

test('keeps short-answer questions as reference-only', () => {
  const [question] = normalizeQuestionBank({
    body: [
      {
        questions: ['请简述机制'],
        type: ['简答题'],
        answers: ['参考答案'],
      },
    ],
  })

  assert.equal(evaluateAnswer(question, '参考答案').comparable, false)
})

test('builds filtered export rows', () => {
  const questions = normalizeQuestionBank({
    body: [
      {
        questions: ['正确答案是 A'],
        type_code: '1',
        options: ['A 项', 'B 项'],
        answers: ['A'],
      },
      {
        questions: ['正确答案是 B'],
        type_code: '1',
        options: ['A 项', 'B 项'],
        answers: ['B'],
      },
    ],
  })

  const rows = buildQuestionExportRows(questions, {
    responses: {
      [questions[0].id]: 0,
      [questions[1].id]: 0,
    },
    submitted: {
      [questions[0].id]: true,
      [questions[1].id]: true,
    },
    favorites: [questions[1].id],
  })

  assert.equal(filterQuestionExportRows(rows, 'wrong').length, 1)
  assert.equal(filterQuestionExportRows(rows, 'favorites')[0].title, '正确答案是 B')
  assert.match(formatExportContent(rows, { title: '导出测试' }, 'txt'), /导出测试/)
  assert.match(formatExportContent(rows, { title: '导出测试' }, 'csv'), /"题目"/)
})
